force-app/main/default/objects/Platform_Unit_of_Work__c/Platform_Unit_of_Work__c.object-meta.xml
<CustomObject>
    <label>Platform Unit of Work</label>
    <nameField>
        <displayFormat>UOW-{00000000}</displayFormat>
        <label>UOW Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Unit of Works</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Creator__c.field-meta.xml
<CustomField>
    <fullName>Creator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Platform_Unit_of_Works</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Next__c.field-meta.xml
<CustomField>
    <fullName>Next__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Next</label>
    <referenceTo>Platform_Unit_of_Work__c</referenceTo>
    <relationshipLabel>Platform Unit of Works (Next)</relationshipLabel>
    <relationshipName>Platform_Unit_of_Works1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Num_of_Children__c.field-meta.xml
<CustomField>
    <fullName>Num_of_Children__c</fullName>
    <label>Num of Children</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Num_of_Error__c.field-meta.xml
<CustomField>
    <fullName>Num_of_Error__c</fullName>
    <label>Num of Error</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Num_of_Success__c.field-meta.xml
<CustomField>
    <fullName>Num_of_Success__c</fullName>
    <label>Num of Success</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Platform_Unit_of_Work__c</referenceTo>
    <relationshipLabel>Platform Unit of Works</relationshipLabel>
    <relationshipName>Platform_Unit_of_Works</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Init</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Ignore</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/UOW_Processor__c.field-meta.xml
<CustomField>
    <fullName>UOW_Processor__c</fullName>
    <label>UOW Processor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work_Config__mdt/Platform_Unit_of_Work_Config__mdt.object-meta.xml
<CustomObject>
    <label>Platform Unit of Work Config</label>
    <pluralLabel>Platform Unit of Work Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Platform_Unit_of_Work_Config__mdt/fields/has_Next__c.field-meta.xml
<CustomField>
    <fullName>has_Next__c</fullName>
    <defaultValue>false</defaultValue>
    <label>has Next</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work_Config__mdt/fields/Ignore_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ignore Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work_Config__mdt/fields/Max_Size__c.field-meta.xml
<CustomField>
    <fullName>Max_Size__c</fullName>
    <label>Max Size</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work_Event__e/Platform_Unit_of_Work_Event__e.object-meta.xml
<CustomObject>
    <label>Platform Unit of Work Event</label>
    <pluralLabel>Platform Unit of Work Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Platform_Unit_of_Work_Event__e/fields/Creator__c.field-meta.xml
<CustomField>
    <fullName>Creator__c</fullName>
    <label>Creator</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work_Event__e/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <label>Parent</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work_Event__e/fields/UOW_Id__c.field-meta.xml
<CustomField>
    <fullName>UOW_Id__c</fullName>
    <label>UOW Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work_Event__e/fields/UOW_Processor__c.field-meta.xml
<CustomField>
    <fullName>UOW_Processor__c</fullName>
    <label>UOW Processor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Platform_UnitOfWorkTriggerHandler.cls
public  class Platform_UnitOfWorkTriggerHandler extends TriggerHandler {
    static boolean isSycncExcuted = false;
    public override void AfterInsert(Map<Id, SObject> newItems) {
        List<Platform_Unit_of_Work__c> syncUows =  new List<Platform_Unit_of_Work__c>();
        for (SObject item: newItems.values()) {
            Platform_Unit_of_Work__c uow = (Platform_Unit_of_Work__c) item;
            System.debug('status: ' + uow.Status__c);
            if (uow.Status__c == 'Queued' && uow.UOW_Processor__c != null) {
                if (uow.UOW_Processor__c.contains('Callout')) {
                    System.enqueueJob(new Platform_UnitOfWorkUtils.UnitOfWorkUtilTask(uow.id));
                } else {
                    syncUows.add(uow);
                }
            }
        }
        // exuecute the first uow in syncUows, and create uow event for the rest
        if (syncUows.size() > 0) {
            if  (!isSycncExcuted) {
                isSycncExcuted = true;
                Platform_Unit_of_Work__c firstUow = syncUows[0];
                Platform_UnitOfWorkUtils.execute(firstUow);
                syncUows.remove(0);
            } 

            for (Platform_Unit_of_Work__c uow : syncUows) {
                Platform_Unit_of_Work_Event__e event = new Platform_Unit_of_Work_Event__e(
                    UOW_Id__c = uow.Id,
                    Creator__c = uow.Creator__c,
                    UOW_Processor__c = uow.UOW_Processor__c,
                    Payload__c = uow.Payload__c,
                    Parent__c = uow.Parent__c,
                    Status__c = uow.Status__c,
                    Description__c = uow.Description__c
                );
                Database.SaveResult sr = EventBus.publish(event);
            }
        }
        /*
        for (Unit_of_Work__c uow : syncUows) {
            System.enqueueJob(new Platform_UnitOfWorkUtils.UnitOfWorkUtilTask(uow.id));
        }*/


        if (newItems.size() == 1) {
            Platform_Unit_of_Work__c uow = (Platform_Unit_of_Work__c) newItems.values()[0];
            if ((uow.Parent__c != null) && (uow.Status__c == 'Success' || uow.Status__c == 'Error')) {
                // find how many child uows are in 'Success' or 'Error' status and update parent uow status
                //update Num_of_Error__c and Num_of_Success__c fields on parent uow
                Platform_Unit_of_Work__c parent = [SELECT Id, Num_of_Error__c, Num_of_Success__c, Num_of_Children__c FROM Platform_Unit_of_Work__c WHERE Id = :uow.Parent__c for update];
                List<Platform_Unit_of_Work__c> childUows = [SELECT Id, Status__c FROM Platform_Unit_of_Work__c WHERE Parent__c = :uow.Parent__c];
                Integer successCount = 0;
                Integer errorCount = 0;
                for (Platform_Unit_of_Work__c childUow : childUows) {
                    if (childUow.Status__c == 'Success') {
                        successCount++;
                    } else if (childUow.Status__c == 'Error') {
                        errorCount++;
                    }
                }
                parent.Num_of_Error__c = errorCount;
                parent.Num_of_Success__c = successCount;
                parent.Num_of_Children__c = childUows.size();
                if (successCount + errorCount == parent.Num_of_Children__c) {
                    if (errorCount > 0) {
                        parent.Status__c = 'Error';
                    } else {
                        parent.Status__c = 'Success';
                    }
                }
                update parent;
            }
        }
    } 

    public override void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        System.debug('AfterUpdate:');
        if (newItems.size() == 1 && ((Platform_Unit_of_Work__c)newItems.values()[0]).Status__c == 'Success' 
                && ((Platform_Unit_of_Work__c)newItems.values()[0]).Parent__c == null 
                && ((Platform_Unit_of_Work__c)oldItems.values()[0]).Status__c != 'Success') {
            Platform_Unit_of_Work__c uow = (Platform_Unit_of_Work__c) newItems.values()[0];
            Platform_Unit_of_Work_Config__mdt    config = [Select Ignore_Eligible__c, Max_Size__c, has_Next__c from Platform_Unit_of_Work_Config__mdt where DeveloperName = :uow.UOW_Processor__c limit 1];
            if (config.has_Next__c) {
                if (uow.Next__c != null) {
                    Platform_Unit_of_Work__c nextUow = new Platform_Unit_of_Work__c();
                    nextUow.Id = uow.Next__c;
                    nextUow.Status__c = 'Queued';
                    update nextUow;
                }
                /*
                else {
                    Type t = Type.forName(null, uow.UOW_Processor__c);
                    Platform_UnitOfWorkAbstractProcessor instance = (Platform_UnitOfWorkAbstractProcessor) t.newInstance();
                    instance.setUowObject(uow);
                    instance.createNext();
                }*/
            }
        }
        AfterInsert(newItems);
    }
}