force-app/main/default/objects/Test__b/Test__b.object-meta.xml
<CustomObject>
    <label>Test</label>
    <pluralLabel>Tests</pluralLabel>
</CustomObject>

force-app/main/default/objects/Test__b/fields/Change_Event__c.field-meta.xml
<CustomField>
    <fullName>Change_Event__c</fullName>
    <label>Change Event</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test__b/fields/Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_Time__c</fullName>
    <label>Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Test__b/fields/Object_ID__c.field-meta.xml
<CustomField>
    <fullName>Object_ID__c</fullName>
    <label>Object ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestBigObjectQuery.cls
public with sharing class TestBigObjectQuery {

    public static List<Test__b> queryTestBigObject(DateTime startDate, DateTime endDate, String objectId) {
        List<Test__b> results = [SELECT Change_Event__c, Date_Time__c, Object_Id__c 
                                 FROM Test__b 
                                 WHERE Object_Id__c = :objectId AND Date_Time__c >= :startDate AND Date_Time__c <= :endDate 
                                 ];

		System.debug(results.size());
        return results;
    }
}