force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Unit_of_Work__c/Platform_Unit_of_Work__c.object-meta.xml
<CustomObject>
    <label>Platform Unit of Work</label>
    <nameField>
        <displayFormat>UOW-{00000000}</displayFormat>
        <label>UOW Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Unit of Works</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Creator__c.field-meta.xml
<CustomField>
    <fullName>Creator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Platform_Unit_of_Works</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Error Log</label>
    <referenceTo>Log__c</referenceTo>
    <relationshipLabel>Platform Unit of Works</relationshipLabel>
    <relationshipName>Platform_Unit_of_Works</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Num_of_Children__c.field-meta.xml
<CustomField>
    <fullName>Num_of_Children__c</fullName>
    <label>Num of Children</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Platform_Unit_of_Work__c</referenceTo>
    <relationshipLabel>Platform Unit of Works</relationshipLabel>
    <relationshipName>Platform_Unit_of_Works</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Init</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Ignore</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/UOW_Processor__c.field-meta.xml
<CustomField>
    <fullName>UOW_Processor__c</fullName>
    <label>UOW Processor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work_Event__e/Platform_Unit_of_Work_Event__e.object-meta.xml
<CustomObject>
    <label>Platform Unit of Work Event</label>
    <pluralLabel>Platform Unit of Work Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Platform_Unit_of_Work_Event__e/fields/Creator__c.field-meta.xml
<CustomField>
    <fullName>Creator__c</fullName>
    <label>Creator</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work_Event__e/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <label>Parent</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work_Event__e/fields/UOW_Processor__c.field-meta.xml
<CustomField>
    <fullName>UOW_Processor__c</fullName>
    <label>UOW Processor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Platform_UnitOfWorkUtils.cls
public with sharing class Platform_UnitOfWorkUtils {
    public static void saveUnitOfWork(Id uowId, String status, Log__c errorLog) {
        saveUnitOfWork(uowId, 0, status, errorLog);
    }

    public static void saveUnitOfWork(Id uowId, Integer numOfChildren, String status, Log__c errorLog) {
        System.debug('status: ' + status);
        Platform_Unit_of_Work__c uow = new Platform_Unit_of_Work__c();
        uow.Id = uowId;
        uow.Status__c = status;
        uow.Num_of_Children__c = numOfChildren;
        uow.Error_Log__c = (errorLog != null) ? errorLog.Id : null;
        try {
            update uow;
        } catch (Exception e) {
            Log.logError(e);
        }
    }

    public static void submit(Platform_UnitOfWork uow, String status) {
        Platform_Unit_of_Work_Event__e  event = new Platform_Unit_of_Work_Event__e(
            Creator__c = UserInfo.getUserId(),
            UOW_Processor__c = uow.uowProcessor,
            Payload__c = JSON.serialize(uow),
            Description__c = uow.description,
            Status__c = status
        );
        Database.SaveResult sr = EventBus.publish(event);
        
    }

    public static void execute(Platform_Unit_of_Work__c uow) {
        try {
            if (uow.UOW_Processor__c.contains('Callout')) {
                    System.enqueueJob(new UnitOfWorkUtilTask(uow.id));
            } else {
                run(uow);
            }
        } catch (Exception e) {
            saveUnitOfWork(uow.id, 'Error', Log.logError(uow.id, e));
        }
    }
    
    public static void run(Platform_Unit_of_Work__c uow) {
        Type t = Type.forName(null, uow.UOW_Processor__c);
        if (t == null) {
            saveUnitOfWork(uow.id, 'Error', Log.logError(uow.id, new Platform_Exception('Invalid class name: ' + uow.UOW_Processor__c)));
            return;
        }
        Platform_UnitOfWorkAbstractProcessor instance = (Platform_UnitOfWorkAbstractProcessor) t.newInstance();
        instance.setUowObject(uow);
        instance.execute();
    }

    public with sharing class UnitOfWorkUtilTask implements System.Queueable, Database.AllowsCallouts{
         String uowId = null;
         public UnitOfWorkUtilTask(String uowId) {
             this.uowId = uowId;
         }
 
         public void execute(System.QueueableContext ctx) {
            String message = null;
            Platform_Unit_of_Work__c uow = [Select Id, Creator__c, Description__c, Error_Log__c,Payload__c, Parent__c,
                            Status__c, UOW_Processor__c, Num_of_Children__c
                            from Platform_Unit_of_Work__c where id = :uowId];
            run(uow);
        }
    }

    public static Platform_UnitOfWork deserializeUnitOfWork(Map<String, Object> jsonMap) {
        // Create the current Platform_UnitOfWork object
        Platform_UnitOfWork obj = new Platform_UnitOfWork(
            (String) jsonMap.get('uowProcessor'),
            (Map<String, Object>) jsonMap.get('parameters'),
            (String) jsonMap.get('description'),
            (String) jsonMap.get('parentId'),
            (String) jsonMap.get('status')
        );
    
        // Handle 'subWorks' recursively
        if (jsonMap.containsKey('subWorks') && jsonMap.get('subWorks') != null) {
            Object subWorksRaw = jsonMap.get('subWorks');
            if (subWorksRaw instanceof List<Object>) {
                List<Object> subWorksList = (List<Object>) subWorksRaw;
                obj.subWorks = new List<Platform_UnitOfWork>();
                for (Object subWorkObj : subWorksList) {
                    if (subWorkObj instanceof Map<String, Object>) {
                        obj.subWorks.add(deserializeUnitOfWork((Map<String, Object>) subWorkObj));
                    } else {
                        System.debug('Unexpected subWorkObj type: ' + subWorkObj);
                    }
                }
            } else {
                System.debug('Unexpected subWorksRaw type: ' + subWorksRaw);
            }
        }
    
        // Handle 'nextWork' recursively
        if (jsonMap.containsKey('nextWork') && jsonMap.get('nextWork') != null) {
            Object nextWorkRaw = jsonMap.get('nextWork');
            if (nextWorkRaw instanceof Map<String, Object>) {
                obj.nextWork = deserializeUnitOfWork((Map<String, Object>) nextWorkRaw);
            } else {
                System.debug('Unexpected nextWorkRaw type: ' + nextWorkRaw);
            }
        }
    
        return obj;
    }

    
}