force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Unit_of_Work__c/Platform_Unit_of_Work__c.object-meta.xml
<CustomObject>
    <label>Platform Unit of Work</label>
    <nameField>
        <displayFormat>UOW-{00000000}</displayFormat>
        <label>UOW Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Unit of Works</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Creator__c.field-meta.xml
<CustomField>
    <fullName>Creator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Platform_Unit_of_Works</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Error Log</label>
    <referenceTo>Log__c</referenceTo>
    <relationshipLabel>Platform Unit of Works</relationshipLabel>
    <relationshipName>Platform_Unit_of_Works</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Next__c.field-meta.xml
<CustomField>
    <fullName>Next__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Next</label>
    <referenceTo>Platform_Unit_of_Work__c</referenceTo>
    <relationshipLabel>Platform Unit of Works (Next)</relationshipLabel>
    <relationshipName>Platform_Unit_of_Works1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Num_of_Children__c.field-meta.xml
<CustomField>
    <fullName>Num_of_Children__c</fullName>
    <label>Num of Children</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Platform_Unit_of_Work__c</referenceTo>
    <relationshipLabel>Platform Unit of Works</relationshipLabel>
    <relationshipName>Platform_Unit_of_Works</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Init</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Ignore</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work__c/fields/UOW_Processor__c.field-meta.xml
<CustomField>
    <fullName>UOW_Processor__c</fullName>
    <label>UOW Processor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work_Config__mdt/Platform_Unit_of_Work_Config__mdt.object-meta.xml
<CustomObject>
    <label>Platform Unit of Work Config</label>
    <pluralLabel>Platform Unit of Work Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Platform_Unit_of_Work_Config__mdt/fields/has_Next__c.field-meta.xml
<CustomField>
    <fullName>has_Next__c</fullName>
    <defaultValue>false</defaultValue>
    <label>has Next</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work_Config__mdt/fields/Ignore_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ignore Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Platform_Unit_of_Work_Config__mdt/fields/Max_Size__c.field-meta.xml
<CustomField>
    <fullName>Max_Size__c</fullName>
    <label>Max Size</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Platform_UnitOfWorkAbstractProcessor.cls
public abstract class Platform_UnitOfWorkAbstractProcessor {

    public Platform_Unit_of_Work__c uowObject;
    public Platform_UnitOfWork uow;
    public Platform_Unit_of_Work_Config__mdt config;
       
    public void setUowObject(Platform_Unit_of_Work__c uowObject) {
        this.uowObject = uowObject;
        config = [Select Ignore_Eligible__c, Max_Size__c, has_Next__c from Platform_Unit_of_Work_Config__mdt where DeveloperName = :uowObject.UOW_Processor__c limit 1];
        uow = (Platform_UnitOfWork) Platform_UnitOfWorkUtils.deserializeUnitOfWork((Map<String, Object>)JSON.deserializeUntyped(uowObject.Payload__c));
    }

    public Platform_Unit_of_Work_Config__mdt getConfig() {
        return config;
    }

    public abstract void process();

    public virtual boolean isEligibleForProcessing() {
        return true;
    }


    public void  execute() {
         
        String status = uowObject.Status__c;
        Log__c errorLog = null;
        Integer numOfChildren = 0;
        try {
            if (uowObject.status__c=='Queued' && uowObject.Num_of_Children__c != null && uowObject.Num_of_Children__c > 0) {
                System.debug('Num_of_Children__c: ' + uowObject.Num_of_Children__c);
                status = 'Processing';
                List<Platform_Unit_of_Work__c> childUows = [SELECT Id, Status__c FROM Platform_Unit_of_Work__c WHERE Parent__c = :uowObject.Id];
                for (Platform_Unit_of_Work__c childUow : childUows) {
                    childUow.Status__c = 'Queued';
                }
                update childUows;
            }
            else {  
                if (uowObject.Num_of_Children__c != null && uowObject.Num_of_Children__c > 0)
                    return;
                //convert uow.Parameters__c to Map<String, Object>
                //boolean hasChildren = false;
                /*
                if (needToSplit()) {
                    numOfChildren = split();
                    hasChildren = true;
                    status = 'Processing';
                }
				
                
                if (hasSubWorks()) {
                    numOfchildren += createSubWorks();
                    hasChildren = true;
                    status = 'Processing';
                }
                */
                //if (!hasChildren) 
                //{
                    if (config.Ignore_Eligible__c || isEligibleForProcessing()) {
                        process();
                        status = 'Success';
                    }
                    else {
                        status = 'Not Eligible';
                    }
                //}
                //createNext();                    
            }
        } catch (Exception e) {
            System.debug('Error processing UOW: ' + uowObject.Id);
            System.debug(e);
            status = 'Error';
            errorLog = Log.logError(e);
        }
        finally {
            Platform_Unit_of_Work__c uowToUpdate = new Platform_Unit_of_Work__c();
            uowToUpdate.Id = uowObject.Id;
            uowToUpdate.Status__c = status;
            if (errorLog != null) {
                uowToUpdate.Error_Log__c = errorLog.Id;
            }
            uowToUpdate.Num_of_Children__c = numOfChildren;
            update uowToUpdate;
        }
    }
/*
    public boolean hasSubWorks() {
        return uow.subWorks != null && uow.subWorks.size() > 0;
    }
    
    public Integer createSubWorks() {
		List<Platform_Unit_of_Work__c> childUows = new List<Platform_Unit_of_Work__c>();        
        for (Platform_UnitOfWork uow : uow.subWorks) {
            Platform_Unit_of_Work__c child = new Platform_Unit_of_Work__c(
                UOW_Processor__c = uow.uowProcessor,
                Payload__c = JSON.serialize(uow),
                Description__c = uow.description,
                Status__c = 'Queued',
                Creator__c = uowObject.Creator__c,
                Parent__c = uowObject.Id
            );
            childUows.add(child);
        }
        insert childUows;
        return uow.subWorks.size();
    }
    */
    /*
    public boolean needToSplit() {
        List<Object> data = (List<Object>) uow.parameters.get('data');
        Integer size = (data == null) ? -1 : data.size();
        Integer maxSize = (config.Max_Size__c == null || (Integer)config.Max_Size__c == -1)? 2147483647 : (Integer)config.Max_Size__c;
        System.debug('size ' + size);
        System.debug('maxSize ' + maxSize);
        return maxSize < size;
    }

    public Integer split() {
        List<Object> data = (List<Object>) uow.parameters.get('data');
        Integer maxSize = (Integer)config.Max_Size__c;
        Integer numOfChildren = 0;
        List<Object> currentData = new List<Object>();
        List<Platform_Unit_of_Work__c> childUows = new List<Platform_Unit_of_Work__c>();
        for (Integer i = 0; i < data.size(); i++) {
            currentData.add((Object)data[i]);
            if (currentData.size() == maxSize || i == data.size() - 1) {
                Map<String, Object> newParams = new Map<String, Object>();
                newParams.put('data', currentData);
                for (String key : uow.parameters.keySet()) {
                    if (key != 'data') {
                        newParams.put(key, uow.parameters.get(key));
                    }
                }
                Platform_UnitOfWork newUow = new Platform_UnitOfWork(uowObject.UOW_Processor__c, newParams, uowObject.Description__c,uowObject.Id);
                Platform_Unit_of_Work__c child = new Platform_Unit_of_Work__c(
                    UOW_Processor__c = uowObject.UOW_Processor__c,
                    Payload__c = JSON.serialize(newUow),
                    Description__c = uowObject.Description__c,
                    Status__c = 'Queued',
                    Creator__c = uowObject.Creator__c,
                    Parent__c = uowObject.Id
                );
                childUows.add(child);
                currentData.clear();
                numOfChildren++;
            }
        }
        insert childUows;
        return numOfChildren;
    }

    public void createNext() {
        if (uow.nextWork != null) {
            Platform_Unit_of_Work__c nextUow = new Platform_Unit_of_Work__c(
                UOW_Processor__c = uowObject.UOW_Processor__c,
                Payload__c = JSON.serialize(uow.nextWork),
                Description__c = uowObject.Description__c,
                Status__c = 'Init',
                Creator__c = uowObject.Creator__c
            );
            insert nextUow;
            Platform_Unit_of_Work__c uowToUpdate = new Platform_Unit_of_Work__c();
            uowToUpdate.Id = uowObject.Id;
            uowToUpdate.Next__c = nextUow.Id;
            update uowObject;
        }
    }
	*/
}